#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 25 -width 15 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Font Awesome 5 Free 12" <<< ": Lock|: Logout|: Reboot|: Shutdown")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) i3-msg exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac